### ISSUE TITLE
Erreur si la valeur recherchée contient une apostrophe

### ISSUE THREAD

**Issue by ChipsVII** [Web-Ex-Machina/contao-utils#6]
J'ai eu la surprise d'avoir des alias d'artistes Discogs avec des apostrophes dedans, et ça ne plait pas à notre Model.

Un petit `str_replace` m'a tiré d'affaire (c'est pas ouf mais mieux que rien).

Le code initial :
https://github.com/Web-Ex-Machina/contao-utils/blob/132d0c9d7eb371435613fcaee0879dfdc0bafcaa/src/Model/Model.php#L216

Le code corrigé :
```php
$arrColumns[] = sprintf("$t.%s %s '%s'", $strField, $strOperator, str_replace("'","\'",$varValue));
```

**Comment by LupusVII** [comment]
Fixed in #8 (should be okay in 0.3.7+ and 0.4.x)

**Comment by ChipsVII** [comment]
Okay, closing issue.
